### PR TITLE
Add cats

### PR DESCRIPTION
**Pull request by t1gu1**
I add the cat animation!
I test it on my nvim config.

I created the walk_left animation for each colors (4) AND I create the cat.lua with the associated animations states.

### CODE REVIEW

**Comment by t1gu1** [comment]
Done for real. No more commit. Except if you ask for something.

**Comment by giusgad** [comment]
The cats were removed because of #26 as I replied in your issue, so I'll have to ask you to rewrite the git history of your pr if you can to remove the assets, and if you want to use them locally you should buy them. Sorry for the inconvenience.

**Comment by mistricky** [comment]
Thx for this PR, That's what I'm looking for, I forked it for personal use

**Comment by giusgad** [comment]
@mistricky You cannot use this PR for personal use, if you want the cats assets you have to buy them. I already asked the creator to delete hot history but it was not done. Do not use this PR, and if you have forked this please remove your repo too.

@t1gu1 you should remove the images by overwriting git history, so that they are no longer accessible to other people

**Comment by mistricky** [comment]
😯 Oh, thank u for the reminder, I just realized what you mentioned, I'll delete the forked repo.

**Comment by t1gu1** [comment]
@giusgad The branch doesn't exist anymore on my side since.
image

The info seems to keep existing in that issue.
image

I may be wrong.
Else, could you explain how can I change that?

**Comment by giusgad** [comment]
@t1gu1 You have to use tools like `BFG repo-cleaner` to rewrite the commit history deleting all data. Try using that, if your branch doesn't exist anymore maybe try recreating it and using the tool to delete the data. If you need further help let me know, if you can't figure it out in a day or two I will just delete the repo and recreate it from scratch. Please report back your if you find you can't do anything about this.

**Comment by t1gu1** [comment]
@giusgad
I just completely delete the fork repository on my side.
But the history is still visible in this pull request... :/

**Comment by giusgad** [comment]
@t1gu1 GitHub support only deletes sensitive data and I'm pretty sure this doesn't count, I'll just recreate the repo as the simpler solution

**Pull request closed without merging**
